services:
  postgresql:
    image: postgres:17.4
    container_name: argydb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgresql

volumes:
  pgdata:

networks:
  postgresql:
